package Sites;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *<pre>
 * Class        About.java
 * Description  About form
 * Platform     jdk 1.8.0_214; Windows 10
 * Date         10/31/2023
 * History log
 * @author	    <i>wldeh</i>
 * @version 	  %1% %4%
 * @see     	  javax.swing.JDialog
 *</pre>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class About extends javax.swing.JDialog {

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Constructor  JDialog to allow to select modal or modeless form
   * Description  Create the form as designed, center it, set the icon,
   *              closeJButton as default.
   * Date         10/31/2023
   * History log
   * @author      <i>wldeh</i>
   * @param       parent java.awt.Frame
   * @param       modal boolean
   * @see         javax.swing.JDialog
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public About(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
    //set closeJButton as default
    this.getRootPane().setDefaultButton(closeJButton);
    this.setLocationRelativeTo(null); //center form
    setDate(); // call a private method to set date in title bar
  }

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Method       setDate()
   * Description  Private method to set current date in the dateJTextField of
   *              the main GUI form in mm/dd/yyyy format
   * @see         java.text.DateFormat
   * @see         java.text.SimpleDateFormat
   * @see         java.util.Date
   * @author      <i>wldeh</i>
   * Date         10/31/2023
   * History log
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  private void setDate() {
    DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
    Date date = new Date();
    dateJLabel.setText("Date: " + dateFormat.format(date));
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    titleJLabel = new javax.swing.JLabel();
    closeJButton = new javax.swing.JButton();
    authorJLabel = new javax.swing.JLabel();
    versionJLabel = new javax.swing.JLabel();
    copyrightJLabel1 = new javax.swing.JLabel();
    dateJLabel = new javax.swing.JLabel();
    infoJScrollPane = new javax.swing.JScrollPane();
    infoJTextArea = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Vacation Sites About Form");
    setResizable(false);

    titleJLabel.setFont(new java.awt.Font("Tempus Sans ITC", 2, 36)); // NOI18N
    titleJLabel.setForeground(new java.awt.Color(0, 102, 102));
    titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    titleJLabel.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/Images/worldFlags_small.GIF")
      )
    ); // NOI18N
    titleJLabel.setText("Vacation Sites About");

    closeJButton.setBackground(new java.awt.Color(204, 255, 204));
    closeJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
    closeJButton.setMnemonic('C');
    closeJButton.setText("Close");
    closeJButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          closeJButtonActionPerformed(evt);
        }
      }
    );

    authorJLabel.setText("Author:  wldeh");

    versionJLabel.setText("Version 1.3.2");

    copyrightJLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    copyrightJLabel1.setText("Copyright: Freeware");

    dateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    dateJLabel.setText("Date:  10/31/2023");

    infoJTextArea.setEditable(false);
    infoJTextArea.setColumns(20);
    infoJTextArea.setFont(new java.awt.Font("Monospaced", 0, 16)); // NOI18N
    infoJTextArea.setLineWrap(true);
    infoJTextArea.setRows(5);
    infoJTextArea.setText(
      "This program tests the user's knowledge of world vacation site. The application displays a random shown world site image and the name of the site and asks the user to select country whose site is shown. The score of correct answers is recorded for the selected players in a binary search tree database of players. The program provides adding, editing, searching, deleting of players as well as details for the selected player and country."
    );
    infoJTextArea.setWrapStyleWord(true);
    infoJScrollPane.setViewportView(infoJTextArea);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(29, 29, 29)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(
                  titleJLabel,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  643,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addGroup(
                  layout
                    .createParallelGroup(
                      javax.swing.GroupLayout.Alignment.LEADING,
                      false
                    )
                    .addComponent(
                      infoJScrollPane,
                      javax.swing.GroupLayout.PREFERRED_SIZE,
                      643,
                      javax.swing.GroupLayout.PREFERRED_SIZE
                    )
                    .addGroup(
                      layout
                        .createSequentialGroup()
                        .addGroup(
                          layout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addComponent(
                              versionJLabel,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              204,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                            .addComponent(
                              authorJLabel,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              204,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addPreferredGap(
                          javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                          javax.swing.GroupLayout.DEFAULT_SIZE,
                          Short.MAX_VALUE
                        )
                        .addComponent(
                          closeJButton,
                          javax.swing.GroupLayout.PREFERRED_SIZE,
                          79,
                          javax.swing.GroupLayout.PREFERRED_SIZE
                        )
                        .addGap(73, 73, 73)
                        .addGroup(
                          layout
                            .createParallelGroup(
                              javax.swing.GroupLayout.Alignment.LEADING
                            )
                            .addComponent(
                              copyrightJLabel1,
                              javax.swing.GroupLayout.Alignment.TRAILING
                            )
                            .addComponent(
                              dateJLabel,
                              javax.swing.GroupLayout.Alignment.TRAILING,
                              javax.swing.GroupLayout.PREFERRED_SIZE,
                              204,
                              javax.swing.GroupLayout.PREFERRED_SIZE
                            )
                        )
                        .addGap(8, 8, 8)
                    )
                )
            )
            .addContainerGap(31, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(23, 23, 23)
            .addComponent(
              titleJLabel,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              77,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(
              infoJScrollPane,
              javax.swing.GroupLayout.DEFAULT_SIZE,
              189,
              Short.MAX_VALUE
            )
            .addGap(18, 18, 18)
            .addGroup(
              layout
                .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addComponent(copyrightJLabel1)
                    .addPreferredGap(
                      javax.swing.LayoutStyle.ComponentPlacement.UNRELATED
                    )
                    .addComponent(dateJLabel)
                )
                .addGroup(
                  layout
                    .createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(versionJLabel)
                )
                .addComponent(
                  closeJButton,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  40,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addComponent(authorJLabel)
            )
            .addGap(24, 24, 24)
        )
    );

    dateJLabel.getAccessibleContext().setAccessibleName("Date:  10/31/2023");

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Method       closeJButtonActionPerformed
   * Description  Closes the About form only.
   * Date         10/31/2023
   * History log
   * @author      <i>wldeh</i>
   * @param       evt java.awt.event.ActionEvent
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_closeJButtonActionPerformed //GEN-HEADEREND:event_closeJButtonActionPerformed
    this.dispose();
  } //GEN-LAST:event_closeJButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel authorJLabel;
  private javax.swing.JButton closeJButton;
  private javax.swing.JLabel copyrightJLabel1;
  private javax.swing.JLabel dateJLabel;
  private javax.swing.JScrollPane infoJScrollPane;
  private javax.swing.JTextArea infoJTextArea;
  private javax.swing.JLabel titleJLabel;
  private javax.swing.JLabel versionJLabel;
  // End of variables declaration//GEN-END:variables
}
