package Sites;

import java.awt.Color;
import java.awt.Toolkit;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *<pre>
 * Class        Edit
 * Description  A class reresenting the GUI used in a maintaining site
 * Date         10/31/2023
 * History Log
 * @author	    <i>wldeh</i>
 * @version 	  %1% %2%
 *</pre>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class Edit extends javax.swing.JDialog {

  // class instance variables
  private Site site = null;
  private boolean error = false;
  private String errorMessage = "";
  private final int MAX_POPULATION = 1000000;
  private final int MIN_POPULATION = 0;
  private final int MAX_AREA = 100000000;
  private final Color white = Color.WHITE; // Default background color for input textfield
  private final Color pink = Color.PINK; // Background color for bad input textfield

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Constructor  Edit()--default constructor
   * Description  Create an instance of the GUI form.
   *              Used for Add Site.
   * Date         10/31/2023
   * History Log  7/18/2018, 5/7/2020
   * @author      <i>wldeh</i>
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public Edit(java.awt.Frame parent, boolean modal) {
    initComponents();
    // set closeJbutton as default
    this.getRootPane().setDefaultButton(saveJButton);
    // set icon
    this.setIconImage(
        Toolkit.getDefaultToolkit().getImage("src/Images/Sites.jpg")
      );
    this.setLocationRelativeTo(null); // center form
    setAlwaysOnTop(true);
    setModal(true);
  }

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Constructor  Edit()--overloaded constructor
   * Description  Create the default construtor to create an instance of the GUI
   *              form and displays information of selected site
   * Date         10/31/2023
   * History Log
   * @author      <i>wldeh</i>
   * @param       site Site
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public Edit(Site site) {
    //this();  //call default constructor
    nameJTextField.setText(site.getName());
    countryJTextField.setText(site.getCountry());
    populationJTextField.setText(String.valueOf(site.getPopulation()));
    capitalJTextField.setText(site.getCapital());
    areaJTextField.setText(String.valueOf(site.getArea()));
    nameJTextField.requestFocus();
    nameJTextField.selectAll();
  }

  /* public Edit(Player parent) {
        initComponents();
        this.setLocationRelativeTo(null);       //center form
    }*/

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    addEditJLabel = new javax.swing.JLabel();
    controlJPanel = new javax.swing.JPanel();
    saveJButton = new javax.swing.JButton();
    cancelJButton = new javax.swing.JButton();
    contentJPanel = new javax.swing.JPanel();
    nameJLabel = new javax.swing.JLabel();
    nameJTextField = new javax.swing.JTextField();
    countryJLabel = new javax.swing.JLabel();
    countryJTextField = new javax.swing.JTextField();
    populationJLabel = new javax.swing.JLabel();
    populationJTextField = new javax.swing.JTextField();
    capitalJLabel = new javax.swing.JLabel();
    capitalJTextField = new javax.swing.JTextField();
    areaJLabel = new javax.swing.JLabel();
    areaJTextField = new javax.swing.JTextField();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    addEditJLabel.setFont(new java.awt.Font("Tempus Sans ITC", 2, 36)); // NOI18N
    addEditJLabel.setForeground(new java.awt.Color(51, 0, 0));
    addEditJLabel.setIcon(
      new javax.swing.ImageIcon(
        getClass().getResource("/Images/worldFlags_small.GIF")
      )
    ); // NOI18N
    addEditJLabel.setText("Edit Vacation Site");

    controlJPanel.setLayout(new java.awt.GridLayout(1, 2, 3, 6));

    saveJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    saveJButton.setMnemonic('S');
    saveJButton.setText("Save");
    saveJButton.setToolTipText("Click to submit your answer");
    saveJButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          saveJButtonActionPerformed(evt);
        }
      }
    );
    controlJPanel.add(saveJButton);

    cancelJButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    cancelJButton.setMnemonic('n');
    cancelJButton.setText("Cancel");
    cancelJButton.setToolTipText("Play all over again!");
    cancelJButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          cancelJButtonActionPerformed(evt);
        }
      }
    );
    controlJPanel.add(cancelJButton);

    contentJPanel.setLayout(new java.awt.GridLayout(5, 2, 2, 2));

    nameJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    nameJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    nameJLabel.setText("Name of Site: \n");
    contentJPanel.add(nameJLabel);

    nameJTextField.setEditable(false);
    nameJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    contentJPanel.add(nameJTextField);

    countryJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    countryJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    countryJLabel.setText("Country:\n\n ");
    contentJPanel.add(countryJLabel);

    countryJTextField.setEditable(false);
    countryJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    contentJPanel.add(countryJTextField);

    populationJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    populationJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    populationJLabel.setText("Population: ");
    contentJPanel.add(populationJLabel);

    populationJTextField.setEditable(false);
    populationJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    contentJPanel.add(populationJTextField);

    capitalJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    capitalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    capitalJLabel.setText("Capital: ");
    contentJPanel.add(capitalJLabel);

    capitalJTextField.setEditable(false);
    capitalJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    contentJPanel.add(capitalJTextField);

    areaJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    areaJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
    areaJLabel.setText("Area: ");
    contentJPanel.add(areaJLabel);

    areaJTextField.setEditable(false);
    areaJTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    contentJPanel.add(areaJTextField);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addContainerGap(63, Short.MAX_VALUE)
            .addComponent(
              addEditJLabel,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              387,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(56, 56, 56)
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(15, 15, 15)
            .addGroup(
              layout
                .createParallelGroup(
                  javax.swing.GroupLayout.Alignment.LEADING,
                  false
                )
                .addComponent(
                  controlJPanel,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  Short.MAX_VALUE
                )
                .addComponent(
                  contentJPanel,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  476,
                  Short.MAX_VALUE
                )
            )
            .addGap(0, 0, Short.MAX_VALUE)
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(34, 34, 34)
            .addComponent(addEditJLabel)
            .addPreferredGap(
              javax.swing.LayoutStyle.ComponentPlacement.RELATED,
              24,
              Short.MAX_VALUE
            )
            .addComponent(
              contentJPanel,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              297,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(
              controlJPanel,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              56,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(26, 26, 26)
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Method       saveJButtonActionPerformed
   * Description  sets the settings
   * Date         10/31/2023
   * History log
   * @author      <i>wldeh</i>
   * @param       evt java.awt.event.ActionEvent
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*//**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Method       cancelJButtonActionPerformed
   * Description  Closes the form
   * Date         10/31/2023
   * History log
   * @author      <i>wldeh</i>
   * @param       evt java.awt.event.ActionEvent
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  private void cancelJButtonActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_cancelJButtonActionPerformed
    this.dispose();
  } //GEN-LAST:event_cancelJButtonActionPerformed

  private void saveJButtonActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_saveJButtonActionPerformed
    // TODO add your handling code here:
  } //GEN-LAST:event_saveJButtonActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger
        .getLogger(Edit.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger
        .getLogger(Edit.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger
        .getLogger(Edit.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger
        .getLogger(Edit.class.getName())
        .log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>
    //</editor-fold>

    /* Create and display the dialog */
    java.awt.EventQueue.invokeLater(
      new Runnable() {
        public void run() {
          Edit dialog = new Edit(new javax.swing.JFrame(), true);
          dialog.addWindowListener(
            new java.awt.event.WindowAdapter() {
              @Override
              public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
              }
            }
          );
          dialog.setVisible(true);
        }
      }
    );
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JLabel addEditJLabel;
  private javax.swing.JLabel areaJLabel;
  private javax.swing.JTextField areaJTextField;
  private javax.swing.JButton cancelJButton;
  private javax.swing.JLabel capitalJLabel;
  private javax.swing.JTextField capitalJTextField;
  private javax.swing.JPanel contentJPanel;
  private javax.swing.JPanel controlJPanel;
  private javax.swing.JLabel countryJLabel;
  private javax.swing.JTextField countryJTextField;
  private javax.swing.JLabel nameJLabel;
  private javax.swing.JTextField nameJTextField;
  private javax.swing.JLabel populationJLabel;
  private javax.swing.JTextField populationJTextField;
  private javax.swing.JButton saveJButton;
  // End of variables declaration//GEN-END:variables
}
