package Sites;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.DecimalFormat;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *<pre>
 * Class        SiteDetail.java
 * Description  A class representing the GUI used to display details of a
 *              selected site.
 * Project      Vacation Sites Quiz
 * Platform     jdk 1.8.0_241; Windows 10
 * Date         10/31/2023
 * History log
 * @author	    <i>wldeh</i>
 * @version 	  %1% %2%
 * @see         javax.swing.JDialog
 * @see         java.awt.Toolkit
 *</pre>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
public class SiteDetail extends javax.swing.JDialog {

  private Site site;

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   * Constructor  SiteDetail()-default constructor
   * Description  Call default constructor with this() in order to create an
   *              instance of the GUI form, and displays all information of
   *              selected site.
   * @param       parent java.awt.Frame
   * @param       modal boolean
   * Date         10/31/2023
   * History log
   * @author      <i>wldeh</i>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public SiteDetail(java.awt.Frame parent, boolean modal) {
    super(parent, modal);
    initComponents();
  }

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   * Constructor  SiteDetail()-overloaded constructor
   * Description  Call default constructor with this() in order to create an
   *              instance of the GUI form, and displays all information of
   *              selected site.
   * @param       site Site
   * Date         10/31/2023
   * History log
   * @author      <i>wldeh</i>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public SiteDetail(Site site) {
    initComponents();
    this.getRootPane().setDefaultButton(closeJButton);
    this.setLocationRelativeTo(null); //center form
    this.site = site;
    setAlwaysOnTop(true);
    setModal(true);
    this.setTitle(site.getName());
    displayInfo(site);
  }

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   * Constructor   displayInfo()
   * Description   Display detail about country in detailJTextArea by reading
   *               information from file named the same as the country
   * Date          10/31/2023
   * History log
   * @author       <i>wldeh</i>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  public void displayInfo(Site theSite) {
    String fileName = "src/data/" + site.getName() + ".txt";
    StringBuilder output = new StringBuilder();
    DecimalFormat integer = new DecimalFormat("#,##0");
    /*File file = new File(fileName);
        Scanner fileScanner = new Scanner(file);
        while(fileScanner.hasNextLine())
        {
        output.append(fileScanner.nextLine());
        }
        fileScanner.close();*/
    //detailJTextArea.setText(output);
    imgJLabel.setIcon(
      new javax.swing.ImageIcon("src/Images/" + site.getCountry() + ".gif")
    );
    output.append("\n\nName: " + theSite.getName());
    output.append("\nCountry: " + theSite.getCountry());
    output.append("\nPopulation: " + theSite.getPopulation() + " millions");
    output.append("\nCapital: " + theSite.getCapital());
    output.append(
      "\nArea in square miles: " + integer.format(theSite.getArea())
    );
    detailJTextArea.setText(output.toString());
    detailJTextArea.setCaretPosition(0);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {
    closeJButton = new javax.swing.JButton();
    detailJScrollPane = new javax.swing.JScrollPane();
    detailJTextArea = new javax.swing.JTextArea();
    imgJLabel = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    closeJButton.setBackground(new java.awt.Color(204, 255, 204));
    closeJButton.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
    closeJButton.setMnemonic('C');
    closeJButton.setText("Close");
    closeJButton.addActionListener(
      new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
          closeJButtonActionPerformed(evt);
        }
      }
    );

    detailJTextArea.setEditable(false);
    detailJTextArea.setColumns(20);
    detailJTextArea.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
    detailJTextArea.setLineWrap(true);
    detailJTextArea.setRows(5);
    detailJTextArea.setWrapStyleWord(true);
    detailJScrollPane.setViewportView(detailJTextArea);

    imgJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    imgJLabel.setText(" ");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
      getContentPane()
    );
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap(27, Short.MAX_VALUE)
            .addComponent(
              detailJScrollPane,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              539,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
        )
        .addGroup(
          layout
            .createSequentialGroup()
            .addGap(168, 168, 168)
            .addComponent(
              closeJButton,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              222,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addContainerGap(
              javax.swing.GroupLayout.DEFAULT_SIZE,
              Short.MAX_VALUE
            )
        )
        .addGroup(
          layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
              layout
                .createSequentialGroup()
                .addContainerGap()
                .addComponent(
                  imgJLabel,
                  javax.swing.GroupLayout.DEFAULT_SIZE,
                  572,
                  Short.MAX_VALUE
                )
                .addContainerGap()
            )
        )
    );
    layout.setVerticalGroup(
      layout
        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(
          javax.swing.GroupLayout.Alignment.TRAILING,
          layout
            .createSequentialGroup()
            .addContainerGap(340, Short.MAX_VALUE)
            .addComponent(
              detailJScrollPane,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              135,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
            .addComponent(
              closeJButton,
              javax.swing.GroupLayout.PREFERRED_SIZE,
              70,
              javax.swing.GroupLayout.PREFERRED_SIZE
            )
            .addGap(18, 18, 18)
        )
        .addGroup(
          layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
              javax.swing.GroupLayout.Alignment.TRAILING,
              layout
                .createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(
                  imgJLabel,
                  javax.swing.GroupLayout.PREFERRED_SIZE,
                  265,
                  javax.swing.GroupLayout.PREFERRED_SIZE
                )
                .addContainerGap(280, Short.MAX_VALUE)
            )
        )
    );

    pack();
  } // </editor-fold>//GEN-END:initComponents

  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   *<pre>
   * Method       closeJButtonActionPerformed
   * Description  Closes the SiteDetail form only.
   * Date         10/31/2023
   * History log
   * @author      <i>wldeh</i>
   * @param       evt java.awt.event.ActionEvent
   *</pre>
   *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  private void closeJButtonActionPerformed(java.awt.event.ActionEvent evt) { //GEN-FIRST:event_closeJButtonActionPerformed
    this.dispose();
  } //GEN-LAST:event_closeJButtonActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton closeJButton;
  private javax.swing.JScrollPane detailJScrollPane;
  private javax.swing.JTextArea detailJTextArea;
  private javax.swing.JLabel imgJLabel;
  // End of variables declaration//GEN-END:variables
}
